### ISSUE TITLE
AppVeyor problems

### ISSUE THREAD

**Issue by sloede** [trixi-framework/Trixi2Vtk.jl#15]
@ranocha Do you have an idea what's going on here?
![image](https://user-images.githubusercontent.com/3637659/91668686-cd05cb80-eb0e-11ea-87f4-505c60a68e45.png)

**Comment by ranocha** [comment]
You released `v0.1.0` not including `appveyor.yml`. We need to make a release including that file.

**Comment by sloede** [comment]
Ah, ok. Thanks for the clarification. No need for a release right now, we'll do it probably later today anyways.
