### ISSUE TITLE
Error when trying to visualise mesh files

### ISSUE THREAD

**Issue by Arpit-Babbar** [trixi-framework/Trixi2Vtk.jl#55]
I was trying to visualise meshes saved by Trixi. I was able to do it for `TreeMesh`
```Julia
using Trixi, Trixi2Vtk
coordinates_min = (-1.0, -1.0) # minimum coordinates (min(x), min(y))
coordinates_max = ( 1.0,  1.0) # maximum coordinates (max(x), max(y))

# Create a uniformly refined mesh with periodic boundaries
mesh = TreeMesh(coordinates_min, coordinates_max,
                initial_refinement_level=4,
                n_cells_max=30_000) # set maximum capacity of tree data structure
Trixi.save_mesh_file(mesh, ".")
trixi2vtk("mesh.h5")
```
and I am able to visualise it, but I can't do the same for `StructuredMesh` or `P4estMesh`.
```Julia
using Trixi, Trixi2Vtk
coordinates_min = (-1.0, -1.0) # minimum coordinates (min(x), min(y))
coordinates_max = ( 1.0,  1.0) # maximum coordinates (max(x), max(y))

cells_per_dimension = (16, 16)

# Create a uniformly refined mesh with periodic boundaries
mesh = StructuredMesh(cells_per_dimension, coordinates_min, coordinates_max)
Trixi.save_mesh_file(mesh, ".")
trixi2vtk("mesh.h5")
```

I get the error pointing to
https://github.com/trixi-framework/Trixi2Vtk.jl/blob/3a78c57ba7e196c9997c359a1cb616ec8c9b41eb/src/vtktools.jl#L136
which is occurring because `visnodes=1`, giving the error
```ERROR: ArgumentError: range(-1.0, stop=1.0, length=1): endpoints differ```.

Is this expected? I realise that the equivalent visualisation can be obtained with a solution plot (again using `trixi2vtk`) so this definitely causes no direct issues.

~~I was just trying to visualise a mesh before solving an equation on it, so I wished to know if this is expected to work.~~

**Comment by ranocha** [comment]
Could you please try running
```julia
trixi2vtk("mesh.h5", nvisnodes=2)
```
to see whether that works? If it does, we should update our defaults in
https://github.com/trixi-framework/Trixi2Vtk.jl/blob/3a78c57ba7e196c9997c359a1cb616ec8c9b41eb/src/convert.jl#L117-L118

**Comment by Arpit-Babbar** [comment]
> If it does, we should update our defaults in
> 
> https://github.com/trixi-framework/Trixi2Vtk.jl/blob/3a78c57ba7e196c9997c359a1cb616ec8c9b41eb/src/convert.jl#L117-L118
> 
> 
> for (possibly) curved meshes.

Yes, changing to `n_visnodes = 2` seems to work well. Giving the keyword argument doesn't work because `n_visnodes = get_default_nvisnodes(nvisnodes, n_nodes, mesh)` is executed for mesh files.

**Comment by ranocha** [comment]
Oh, crap, that should really be revised... Thanks for checking!
